local M = {
  exclude_explorer_files = { ".git", ".svn", ".hg", "CSV", ".DS_Store", "thumbs.db" },
  blend = 10,
  border = false,
  uifiletypes = {
    "aerial",
    "checkhealth",
    "cmp_docs",
    "cmp_menu",
    "dap-repl",
    "dapui_breakpoints",
    "dapui_console",
    "dapui_hover",
    "dapui_scopes",
    "dapui_stacks",
    "dapui_watches",
    "DressingInput",
    "DressingSelect",
    "fzf",
    "help",
    "lazy",
    "lspinfo",
    "man",
    "mason",
    "neo-tree",
    "netrw",
    "noice",
    "null-ls-info",
    "qf",
    "spectre_panel",
    "TelescopePrompt",
  },
  kind_icons = {
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "ﳠ",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
}

M.exclude_search_files =
  vim.list_extend({ "node_modules", "bower_components", "*.code-search" }, M.exclude_explorer_files)

return M
