return {
  minimal_setup = false,
  open_file_event = { "BufNewFile", "BufRead", "BufAdd", "SessionLoadPost" },
  exclude_explorer_files = { ".git", ".svn", ".hg", "CSV", ".DS_Store", "thumbs.db" },
  exclude_search_files = {
    ".git",
    ".svn",
    ".hg",
    "CSV",
    ".DS_Store",
    "thumbs.db",
    "node_modules",
    "bower_components",
    "*.code-search",
  },
  blend = 10,
  border = "rounded",
  uifiletypes = {
    "aerial",
    "checkhealth",
    "dap-repl",
    "dapui_breakpoints",
    "dapui_console",
    "dapui_hover",
    "dapui_scopes",
    "dapui_stacks",
    "dapui_watches",
    "DressingInput",
    "DressingSelect",
    "neo-tree",
    "lazy",
    "lspinfo",
    "mason",
    "nerdterm",
    "noice",
    "null-ls-info",
    "qf",
    "spectre_panel",
    "TelescopePrompt",
  },
  kind_icons = {
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "ﳠ",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
  signs_priority = { smoothcursor = 11, diagnostic = 9, lightbulb = 8, git = 7 },
}
